spring:
  mail:
    host: smtp.gmail.com
    username: fseproject2519@gmail.com
    password: Fseproject@2519
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true