spring:
  mail:
    host: smtp.gmail.com
    username: someemail@gmail.com
    password: set a password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true